### ISSUE TITLE
Integrate GitHub Workflow Actions

### ISSUE THREAD

**Issue by peter279k** [antidot-framework/docker-dev-server#1]
As title, to make Docker image verified/reliable, I think it's good to integrate GitHub Actions to do Docker image building on upcoming commits/PRs.

**Comment by kpicaza** [comment]
Sounds good, I'm not familiarized with Github actions usage yet, it could be an option to learn.:-)

**Comment by peter279k** [comment]
Don't be worried about that!

I can help you to resolve this issue :)
